plugins {
    id 'java-library'
}

dependencies {
    api project(':cdm')
    implementation project(':persistence')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'io.github.resilience4j:resilience4j-circuitbreaker:2.3.0'
    implementation 'io.github.resilience4j:resilience4j-retry:2.3.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
