plugins {
  id 'org.springframework.boot'
}

dependencies {
  implementation project(':web')
  implementation project(':ingestion')
  implementation 'org.springframework.boot:spring-boot-starter'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springframework.boot:spring-boot-micrometer-observation'
  implementation 'org.springframework.boot:spring-boot-micrometer-tracing-opentelemetry'
  implementation 'io.micrometer:micrometer-tracing-bridge-otel'
  implementation 'io.micrometer:micrometer-registry-prometheus'
  runtimeOnly 'org.postgresql:postgresql'
  runtimeOnly 'io.opentelemetry:opentelemetry-exporter-otlp'
  implementation 'io.opentelemetry:opentelemetry-sdk-extension-autoconfigure'
}

bootJar {
  mainClass = "com.tickonomics.TickonomicsApplication"
}
