/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/kpi/ili": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Institutional Liquidity Index (ILI) value with components. */
        get: operations["getIli"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/ili/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ILI time-series history. */
        get: operations["getIliHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/liquidity-stress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liquidity Stress Index. */
        get: operations["getLiquidityStress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/repo-equity-beta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repo/Equity Beta per symbol. */
        get: operations["getRepoEquityBeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/rrp-drain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reverse Repo Facility (RRP) drain velocity. */
        get: operations["getRrpDrain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/systemic-risk-heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Systemic risk heatmap data. */
        get: operations["getSystemicRiskHeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/volatility-regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volatility regime status. */
        get: operations["getVolatilityRegime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/evt-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extreme Value Theory (EVT) risk metrics (v5.2). */
        get: operations["getEvtRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/efficiency-gap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market efficiency gap KPI (v5.1). */
        get: operations["getEfficiencyGap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kpi/monetary-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monetary policy KPI (v5.1). */
        get: operations["getMonetaryPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent signals with filters. */
        get: operations["listSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single signal detail. */
        get: operations["getSignal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current configuration snapshot. */
        get: operations["getConfig"];
        /** Update hot-reloadable configuration. */
        put: operations["updateConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration change log. */
        get: operations["getConfigHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated system health. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Virtual portfolio summary. */
        get: operations["getDemoPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open virtual positions. */
        get: operations["getDemoPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paper trade history. */
        get: operations["getDemoTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/signal-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal quality report. */
        get: operations["getDemoSignalQuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/execution-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dual portfolio P&L execution comparison (v5). */
        get: operations["getDemoExecutionComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/close-position/{positionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a virtual position at the given price. */
        post: operations["closeDemoPosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomaly/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autoencoder anomaly detection on a submitted data window (v4). */
        post: operations["detectAnomaly"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drift/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drift-diffusion simulation for parameter trajectories (v4). */
        post: operations["simulateDrift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/garch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GARCH regime status and conditional variance classification (v4). */
        get: operations["getRegimeGarch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CNN-LSTM hybrid regime status and ensemble classification (v4). */
        get: operations["getRegimeHybrid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/qed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** QED market dynamics status and crash probability (v4). */
        get: operations["getRegimeQed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regime/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A/B comparison of all regime detectors (v4). */
        get: operations["compareRegimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disaster/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disaster alert status from USGS/GDACS feeds (v4). */
        post: operations["submitDisasterAlerts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Participation governance admissibility decomposition (v4). */
        get: operations["getParticipationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stress/liquidity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Liquidity stress test execution (Swiss franc model) (v4). */
        post: operations["runLiquidityStress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bayesian/Firefly optimizer status and last result (v4). */
        get: operations["getOptimizationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimization/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a weight optimization run (v4). */
        post: operations["runOptimization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sentiment/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Model-based (FinBERT) sentiment scores with certainty (v5). */
        post: operations["analyzeSentiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sentiment/lexicon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lexicon (SALI/AFINN) sentiment scores (v5). */
        post: operations["lexiconSentiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Markov optimal stop levels (v5). */
        post: operations["calibrateStops"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leverage/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current leverage rotation signal (v5). */
        get: operations["getLeverageStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pairs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active pairs with divergence status (v5). */
        get: operations["getActivePairs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistical diagnostics (QQ-plot, ACF, convergence) (v5.1). */
        post: operations["computeDiagnostics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/volatility/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Volatility forecast (v5.1). */
        get: operations["getVolatilityForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournament/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Multi-model tournament benchmark (v5.1). */
        post: operations["evaluateTournament"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explainability/feature-importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feature-importance attribution (v5.1). */
        post: operations["explainFeatureImportance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixed-income/q-world-fair-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixed-income Q-world fair value via CIR model (v5.1). */
        get: operations["getQWorldFairValue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fixed-income/tbill-greeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytical T-Bill Greeks (v5.1). */
        get: operations["getTbillGreeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/strategies/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all active strategies and their current status. */
        get: operations["getActiveQuantStrategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/strategies/options/butterfly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate butterfly spread signal (Eq. 79-100). */
        post: operations["computeButterflySignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/signals/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve currently active alpha signals. */
        get: operations["getActiveQuantSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/risk/tail-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Generalized Pareto Distribution (GPD) parameters for tail-risk assessment. */
        get: operations["getTailParameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/risk/evt-tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve EVT tail model output including IRF vectors. */
        get: operations["getEvtTail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/macro/shock-response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve structural VAR impulse response for macro shock analysis. */
        get: operations["getShockResponse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/audit/intersubjective-reproducibility/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forensic reconstruction path (Coding Rules) for a specific data point. */
        get: operations["getAuditPath"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description CDM-aligned rate/instrument identifier (mirrors cdm RateType enum).
         * @enum {string}
         */
        RateType: "SOFR" | "EFFR" | "TGCR" | "BGCR" | "IORB" | "OBFR" | "RRP" | "TGA" | "WALCL" | "TBILL_3M" | "TBILL_1M" | "TBILL_6M" | "TBILL_1Y" | "TBILL_2Y" | "TBILL_5Y" | "TBILL_10Y" | "TBILL_30Y" | "VIX" | "OIL_WTI" | "OIL_BRENT" | "GOLD";
        /**
         * @description CDM product taxonomy (mirrors cdm InstrumentType enum).
         * @enum {string}
         */
        InstrumentType: "SOFR" | "EFFR" | "TGCR" | "BGCR" | "IORB" | "OBFR" | "REPO" | "BILL_3M" | "EQUITY" | "COMMODITY_OIL" | "COMMODITY_GOLD";
        /** @enum {string} */
        OptionType: "CALL" | "PUT";
        /** @enum {string} */
        SignalDirection: "LONG" | "SHORT" | "NEUTRAL";
        Error: {
            /** Format: date-time */
            timestamp: string;
            status: number;
            message: string;
            path?: string;
        };
        AlphaSignal: {
            /** Format: date-time */
            timestamp: string;
            /** Format: uuid */
            strategyId: string;
            symbol: string;
            direction: components["schemas"]["SignalDirection"];
            /** Format: double */
            strength?: number;
            /** Format: double */
            confidence?: number;
            /** Format: double */
            expected_move?: number;
            metrics?: {
                [key: string]: number;
            };
        };
        StrategyStatus: {
            /** Format: uuid */
            id?: string;
            name?: string;
            category?: string;
            formula_refs?: string[];
            active?: boolean;
        };
        EvtMetric: {
            /** Format: double */
            shape_xi?: number;
            /** Format: double */
            scale_beta?: number;
            /** Format: double */
            threshold_u?: number;
            /** Format: double */
            tail_var_999?: number;
        };
        IrfVector: {
            horizon?: number[];
            response_path?: number[];
            confidence_high?: number[];
            confidence_low?: number[];
        };
        IntersubjectivePath: {
            /** Format: uuid */
            signalId?: string;
            path?: {
                ruleName?: string;
                ruleVersion?: string;
                inputHash?: string;
                /** Format: double */
                outputValue?: number;
                /** Format: double */
                irScore?: number;
            }[];
        };
        IliSnapshot: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: double */
            value?: number;
            regime?: string;
            components?: {
                rateType?: components["schemas"]["RateType"];
                /** Format: double */
                weight?: number;
                /** Format: double */
                contribution?: number;
            }[];
        };
        IliHistory: {
            points?: {
                /** Format: date-time */
                timestamp?: string;
                /** Format: double */
                value?: number;
            }[];
        };
        LiquidityStress: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: double */
            index?: number;
            classification?: string;
        };
        RepoEquityBeta: {
            symbol?: string;
            /** Format: double */
            beta?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        RrpDrain: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: double */
            facilityBalance?: number;
            /** Format: double */
            drainVelocity?: number;
        };
        SystemicRiskHeatmap: {
            /** Format: date-time */
            timestamp?: string;
            dimensions?: {
                name?: string;
                /** Format: double */
                score?: number;
            }[];
        };
        VolatilityRegime: {
            /** Format: date-time */
            timestamp?: string;
            regime?: string;
            /** Format: double */
            conditionalVariance?: number;
        };
        EvtRiskMetrics: components["schemas"]["EvtMetric"] & {
            /** Format: date-time */
            timestamp?: string;
            exceedanceCount?: number;
        };
        EfficiencyGap: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: double */
            gap?: number;
        };
        MonetaryPolicy: {
            /** Format: date-time */
            timestamp?: string;
            stance?: string;
            /** Format: double */
            surprise?: number;
        };
        Signal: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            timestamp?: string;
            symbol?: string;
            direction?: components["schemas"]["SignalDirection"];
            /** Format: uuid */
            strategyId?: string;
            status?: string;
        };
        SignalDetail: components["schemas"]["Signal"] & {
            /** Format: double */
            strength?: number;
            /** Format: double */
            confidence?: number;
            metrics?: {
                [key: string]: number;
            };
        };
        /** @description Key/value snapshot of the active configuration. */
        ConfigSnapshot: {
            [key: string]: unknown;
        };
        /** @description Partial configuration update to apply. */
        ConfigUpdate: {
            [key: string]: unknown;
        };
        ConfigHistoryEntry: {
            /** Format: date-time */
            timestamp?: string;
            author?: string;
            changes?: {
                [key: string]: unknown;
            };
        };
        HealthStatus: {
            /** @enum {string} */
            status?: "UP" | "DOWN" | "DEGRADED";
            components?: {
                [key: string]: string;
            };
        };
        DemoPortfolio: {
            /** Format: double */
            balance?: number;
            /** Format: double */
            initialBalance?: number;
            /** Format: double */
            realizedPnl?: number;
            /** Format: double */
            unrealizedPnl?: number;
            /** Format: double */
            totalPnl?: number;
            openPositions?: number;
            totalTrades?: number;
            /** Format: double */
            winRate?: number;
            enabled?: boolean;
        };
        DemoPosition: {
            /** Format: int64 */
            id?: number;
            symbol?: string;
            direction?: components["schemas"]["SignalDirection"];
            /** Format: double */
            quantity?: number;
            /** Format: double */
            entryPrice?: number;
            /** Format: double */
            currentPrice?: number;
            /** Format: double */
            unrealizedPnl?: number;
            /** Format: double */
            stopLossPrice?: number;
            /** Format: double */
            takeProfitPrice?: number;
            /** Format: date-time */
            openedAt?: string;
        };
        DemoTrade: {
            /** Format: int64 */
            id?: number;
            symbol?: string;
            direction?: components["schemas"]["SignalDirection"];
            /** Format: double */
            quantity?: number;
            /** Format: double */
            fillPrice?: number;
            /** Format: double */
            commission?: number;
            /** Format: double */
            slippage?: number;
            /** Format: double */
            realizedPnl?: number;
            /** Format: date-time */
            executedAt?: string;
            tradeType?: string;
        };
        /** @description Signal quality report (hit rate, false-positive rate, breakdowns). */
        SignalQuality: {
            [key: string]: unknown;
        };
        ExecutionComparison: {
            /** Format: double */
            benchmarkPnl?: number;
            /** Format: double */
            managedPnl?: number;
            /** Format: double */
            delta?: number;
        };
        DemoCloseResult: {
            /** Format: int64 */
            tradeId?: number;
            /** Format: int64 */
            positionId?: number;
            /** Format: double */
            realizedPnl?: number;
            /** Format: double */
            fillPrice?: number;
        };
        AnomalyDetectionRequest: {
            series: number[];
            /** Format: double */
            mseThresholdMultiplier?: number;
        };
        AnomalyDetectionResult: {
            scores?: number[];
            /** Format: double */
            reconstructionError?: number;
            /** Format: double */
            threshold?: number;
            isAnomalous?: boolean;
        };
        DriftSimulationRequest: {
            steps: number;
            /** Format: double */
            drift?: number;
            /** Format: double */
            volatility?: number;
        };
        DriftSimulationResult: {
            trajectory?: number[];
            /** Format: double */
            drift?: number;
            /** Format: double */
            volatility?: number;
        };
        RegimeStatus: {
            detector?: string;
            regime?: string;
            /** Format: double */
            crashProbability?: number;
            /** Format: double */
            conditionalVariance?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        RegimeComparison: {
            detectors?: components["schemas"]["RegimeStatus"][];
        };
        DisasterAlert: {
            /** @enum {string} */
            source?: "USGS" | "GDACS";
            eventId?: string;
            severity?: string;
            title?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DisasterAlertBatch: {
            alerts?: components["schemas"]["DisasterAlert"][];
        };
        ParticipationStatus: {
            admissible?: boolean;
            decomposition?: {
                [key: string]: number;
            };
        };
        LiquidityStressRequest: {
            /** Format: double */
            shockBps: number;
            symbol?: string;
        };
        LiquidityStressResult: {
            symbol?: string;
            /** Format: double */
            shockBps?: number;
            /** Format: double */
            priceImpactBps?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        OptimizationStatus: {
            /** @enum {string} */
            method?: "bayesian" | "firefly";
            /** Format: date-time */
            lastRunAt?: string;
            /** Format: double */
            sharpeImprovement?: number;
        };
        OptimizationProposal: {
            weights?: {
                rateType?: components["schemas"]["RateType"];
                /** Format: double */
                weight?: number;
            }[];
            /** Format: double */
            expectedSharpe?: number;
        };
        SentimentRequest: {
            text: string;
        };
        SentimentResult: {
            /** Format: double */
            score?: number;
            /** @enum {string} */
            label?: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
            /** Format: double */
            certainty?: number;
        };
        StopCalibrationRequest: {
            symbol: string;
            horizonBars?: number;
        };
        StopCalibrationResult: {
            symbol?: string;
            /** Format: double */
            optimalStopPct?: number;
            /** Format: double */
            takeProfitPct?: number;
        };
        LeverageStatus: {
            /** @enum {string} */
            signal?: "LEVERAGE_ON" | "LEVERAGE_OFF";
            /** Format: double */
            targetExposure?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        Pair: {
            legs?: string[];
            divergenceStatus?: string;
            /** Format: double */
            zScore?: number;
        };
        DiagnosticsRequest: {
            series: number[];
            lags?: number;
        };
        DiagnosticsResult: {
            qqPoints?: {
                [key: string]: number;
            }[];
            acf?: number[];
            converged?: boolean;
        };
        VolatilityForecast: {
            symbol?: string;
            horizon?: number;
            /** Format: double */
            forecast?: number;
            /** Format: double */
            confidenceHigh?: number;
            /** Format: double */
            confidenceLow?: number;
        };
        TournamentRequest: {
            symbols: string[];
        };
        TournamentResult: {
            rankings?: {
                model?: string;
                /** Format: double */
                score?: number;
            }[];
        };
        ExplainabilityRequest: {
            target: string;
            features?: string[];
        };
        FeatureImportance: {
            attributions?: {
                [key: string]: number;
            };
        };
        QWorldFairValue: {
            rateType?: components["schemas"]["RateType"];
            /** Format: double */
            fairValue?: number;
            /** Format: date-time */
            timestamp?: string;
        };
        TbillGreeks: {
            rateType?: components["schemas"]["RateType"];
            /** Format: double */
            delta?: number;
            /** Format: double */
            gamma?: number;
            /** Format: double */
            vega?: number;
            /** Format: double */
            theta?: number;
        };
    };
    responses: {
        /** @description Invalid request payload or parameters. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        UuidPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIli: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current ILI snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IliSnapshot"];
                };
            };
        };
    };
    getIliHistory: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated ILI history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IliHistory"];
                };
            };
        };
    };
    getLiquidityStress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liquidity stress snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidityStress"];
                };
            };
        };
    };
    getRepoEquityBeta: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repo/equity beta readings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoEquityBeta"][];
                };
            };
        };
    };
    getRrpDrain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RRP drain velocity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RrpDrain"];
                };
            };
        };
    };
    getSystemicRiskHeatmap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Systemic risk heatmap. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemicRiskHeatmap"];
                };
            };
        };
    };
    getVolatilityRegime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Volatility regime. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityRegime"];
                };
            };
        };
    };
    getEvtRisk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EVT risk metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvtRiskMetrics"];
                };
            };
        };
    };
    getEfficiencyGap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Efficiency gap. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EfficiencyGap"];
                };
            };
        };
    };
    getMonetaryPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monetary policy summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonetaryPolicy"];
                };
            };
        };
    };
    listSignals: {
        parameters: {
            query?: {
                symbol?: string;
                direction?: components["schemas"]["SignalDirection"];
                status?: string;
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered signal list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signal"][];
                };
            };
        };
    };
    getSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signal detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSnapshot"];
                };
            };
        };
    };
    updateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdate"];
            };
        };
        responses: {
            /** @description Updated configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getConfigHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration change history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigHistoryEntry"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getDemoPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoPortfolio"];
                };
            };
        };
    };
    getDemoPositions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open positions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoPosition"][];
                };
            };
        };
    };
    getDemoTrades: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paper trades. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoTrade"][];
                };
            };
        };
    };
    getDemoSignalQuality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signal quality report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalQuality"];
                };
            };
        };
    };
    getDemoExecutionComparison: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionComparison"];
                };
            };
        };
    };
    closeDemoPosition: {
        parameters: {
            query: {
                price: number;
            };
            header?: never;
            path: {
                positionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resulting close trade. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoCloseResult"];
                };
            };
        };
    };
    detectAnomaly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnomalyDetectionRequest"];
            };
        };
        responses: {
            /** @description Anomaly scores with MSE threshold classification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyDetectionResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    simulateDrift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriftSimulationRequest"];
            };
        };
        responses: {
            /** @description Drift-diffusion trajectory with Ito process parameters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftSimulationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getRegimeGarch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GARCH regime status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeStatus"];
                };
            };
        };
    };
    getRegimeHybrid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hybrid regime status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeStatus"];
                };
            };
        };
    };
    getRegimeQed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QED regime status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeStatus"];
                };
            };
        };
    };
    compareRegimes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Side-by-side regime comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeComparison"];
                };
            };
        };
    };
    submitDisasterAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisasterAlertBatch"];
            };
        };
        responses: {
            /** @description Acknowledged disaster alerts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisasterAlertBatch"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getParticipationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Participation governance status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipationStatus"];
                };
            };
        };
    };
    runLiquidityStress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiquidityStressRequest"];
            };
        };
        responses: {
            /** @description Liquidity stress test results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidityStressResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getOptimizationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Optimizer status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationStatus"];
                };
            };
        };
    };
    runOptimization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New weight proposal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationProposal"];
                };
            };
        };
    };
    analyzeSentiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SentimentRequest"];
            };
        };
        responses: {
            /** @description Model sentiment scores. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    lexiconSentiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SentimentRequest"];
            };
        };
        responses: {
            /** @description Lexicon sentiment scores. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    calibrateStops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopCalibrationRequest"];
            };
        };
        responses: {
            /** @description Optimal stop levels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopCalibrationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLeverageStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leverage status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeverageStatus"];
                };
            };
        };
    };
    getActivePairs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active pairs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pair"][];
                };
            };
        };
    };
    computeDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticsRequest"];
            };
        };
        responses: {
            /** @description Diagnostic statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getVolatilityForecast: {
        parameters: {
            query?: {
                symbol?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Volatility forecast. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityForecast"];
                };
            };
        };
    };
    evaluateTournament: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentRequest"];
            };
        };
        responses: {
            /** @description Tournament results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    explainFeatureImportance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainabilityRequest"];
            };
        };
        responses: {
            /** @description Feature importance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureImportance"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getQWorldFairValue: {
        parameters: {
            query?: {
                rateType?: components["schemas"]["RateType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Q-world fair value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QWorldFairValue"];
                };
            };
        };
    };
    getTbillGreeks: {
        parameters: {
            query?: {
                maturity?: components["schemas"]["RateType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description T-Bill Greeks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TbillGreeks"];
                };
            };
        };
    };
    getActiveQuantStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active strategies with formula references. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyStatus"][];
                };
            };
        };
    };
    computeButterflySignal: {
        parameters: {
            query: {
                underlying: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Butterfly spread signal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlphaSignal"];
                };
            };
        };
    };
    getActiveQuantSignals: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active alpha signals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlphaSignal"][];
                };
            };
        };
    };
    getTailParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GPD tail parameters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvtMetric"];
                };
            };
        };
    };
    getEvtTail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description EVT tail model output. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        irfVector?: components["schemas"]["IrfVector"];
                    };
                };
            };
        };
    };
    getShockResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Structural VAR impulse response. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        irfVector?: components["schemas"]["IrfVector"];
                    };
                };
            };
        };
    };
    getAuditPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intersubjective reproducibility path. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntersubjectivePath"];
                };
            };
        };
    };
}
